### ISSUE TITLE
want to recommend that you set up a travis-ci build for cinnamon

### ISSUE THREAD

**Issue by andyglick** [MagenTys/cinnamon#11]
I have found that configuring a travis-ci is a great way to get CI information from a free 3rd party service. A particularly nice feature is that you can configure travis to build pull requests against your project automatically.

If you would like me to set up a travis build, I could do that and then you could use my configuration as your own if and when you decide to configure a travis build of your own.

So please let me know

**Comment by mplord** [comment]
@davebassan comments on this?

**Comment by marcelloromani** [comment]
We set up a travis-ci integration in https://github.com/MagenTys/cinnamon/commit/95200293fc314f9e057f35807a2310a0209a6a23
Suggestions welcome!
