### ISSUE TITLE
Latest updates in cinnamon is making the screen shots not to appear the cucumber failure reports

### ISSUE THREAD

**Issue by Hraj** [MagenTys/cinnamon#28]
Latest update guess done on 11 of Jan has removed the screenshots from our cucumber reports for the failed scenarios - as a work around we are using the old Jars of 28th Nov

Can you please fix this issue at the earliest

**Comment by davebassan** [comment]
Hi. Can you provide the version of cinnamon you are using? I see that the last change in Jan was only an update to the README.

Could you also provide details on which cucumber reports you are generating. It would be helpful if you could provide a snippet from your pom (assuming you are using maven)

Thanks
