### ISSUE TITLE
Cinnamon version

### ISSUE THREAD

**Issue by flisowski** [MagenTys/cinnamon#42]
Hey there,
When are you planning to release cinnamon 0.1.4? pom.xml of that version contains latest WebDriverManager version from bonigarcia - 3.4.0, whereas 0.1.3 is still very much out of date with 1.7.0. It is causing a lot of grief with driver binaries management. 

Regards,
Filip

**Comment by davebassan** [comment]
Hi Filip. I have just release version 0.2.0. You will need to refer to the migrating section in the README if you plan to use it.
